app:
  port: 8080
  env: development
  salt: "salt"

auth:
  jwtSecret: "secret"
  jwtExp: 15
  jwtRefreshSecret: "refresh_secret"
  jwtRefreshExp: 10080

db:
  host: 192.168.56.56
  port: 3306
  user: homestead
  password: secret
  database: go_api

redis:
  host: 192.168.56.56
  port: 6379
  password: 
  database: 0
  poolSize: 10
