app:
  port: 8080
  env: development
  salt: "salt"

auth:
  jwt_secret: "secret"
  jwt_exp: 15
  jwt_refresh_secret: "refresh_secret"
  jwt_refresh_exp: 10080

db:
  type: "mysql"
  host: 192.168.56.56
  port: 3306
  user: homestead
  password: secret
  database: go_api
